#cloud-config
users: # Collection von Benutzern
  - name: ubuntu # Der Benutzername des ersten Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Gruppen definieren
    home: /home/ubuntu # Ort von home bestimmen
    shell: /bin/bash # Ort von shell bestimmen
ssh_authorized_keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZtDhe2cNJFNb/BWsXEC9W1xfHlQZvMHIQPhvH4aRBoNyYkBcU2uy9sQAGHiN+T85cgq1tj4jqCW4qBPufER6FdP99vV7qpxfDCXWWNy4ZVpF6qqzbGUKhDP7fbViO2rgB7wD8fHpqxyMlcAK5p6bdVpazHxriMTh3m0RlARapY/FmryhmzjkMY2qG79w+3Xn2TrpTUGCidgKWAa++sqDzAbZ8EvHgSJWKWvFyawXGpIYBsNiJ3aJMADrKjSGCM+Y9PGQbd8WAseN7KgEX9gmASm1iR+dhqYy87qQxo4pjnumqOuF5N5l/UWw0cpayyW89QpzcI8DuH/sox5GkAWYB aws-key
ssh_pwauth: false # Ein boolean Wert. Es bestimmt ob eine Passwort-Authentication aktiviert oder deaktiviert ist
disable_root: false # Regel für Root bestimment
package_update: true
packages: # Collection von Packages
  - apache2 
  - curl 
  - wget 
  - php 
  - libapache2-mod-php 
  - php-mysqli
  - adminer

runcmd:
 - sudo a2enconf adminer 
 - sudo systemctl restart apache2   
 
write_files:
  - content: |
      <?php
          //database
          $servername = "18.205.247.221";
          $username = "admin";
          $password = "password";
          $dbname = "mysql";
          // Create connection
          $conn = new mysqli($servername, $username, $password, $dbname);
          // Check connection
          if ($conn->connect_error) {
                  die("Connection failed: " . $conn->connect_error);
          }
          $sql = "select Host, User from mysql.user;";
          $result = $conn->query($sql);
          while($row = $result->fetch_assoc()){
                  echo($row["Host"] . " / " . $row["User"] . "<br />");
          }
          //var_dump($result);
      ?>   
    path: /var/www/html/db.php
    permission: '0644'
  - content: |
      <?php

      // Show all information, defaults to INFO_ALL
      phpinfo();

      ?>    
    path: /var/www/html/info.php
    permission: '0644'
